repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.2
  hooks:
  - id: seed-isort-config
    args: [--exclude=tests/.*\.py]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    additional_dependencies:
      - toml
