name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install Poetry
      run: pip install "poetry==1.0.0b5"

    - name: Cache Virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Poetry Cache Configuration
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Package Build
      run: poetry build

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.code_climate_id }}
      with:
        coverageCommand: poetry run pytest

    - name: Publish to PyPI
      if: success() && startsWith(github.event.ref, 'refs/tags')
      env:
        TOKEN: ${{ secrets.pypi_token }}
      run: poetry publish -u __token__ -p $TOKEN
